# -*- coding: utf-8 -*-
"""capCount

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13WTBSCE9q_oP2Hptk4u1K6aFOc6NCLth
"""

import sys

def count_capitals_and_indices(s):
    # Initialize variables to store the count of capital letters and the sum of their indices
    capital_count = 0
    indices_sum = 0

    # Iterate over the string and check for capital letters
    for i, char in enumerate(s):
        if char.isupper():
            capital_count += 1
            indices_sum += i

    # Print the results
    print(capital_count)
    print(indices_sum)

if __name__ == "__main__":
    # Check if the input string is provided as a command line argument
    if len(sys.argv) > 1:
        input_string = sys.argv[1]
    else:
        # Read input from standard input if no command line argument is provided
        input_string = input().strip()

    # Call the function with the input string
    count_capitals_and_indices(input_string)