# -*- coding: utf-8 -*-
"""commonset

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dcz4fcFCHNGv5uvGuQYInABxL6IohtVu
"""

import sys

def find_common_words(set_a, set_b):
    # Convert lists to sets
    set_a = set(set_a)
    set_b = set(set_b)

    # Find common words between the sets
    common_words = set_a.intersection(set_b)

    # Print the common words in set format
    print(common_words)

if __name__ == "__main__":
    # Load the variables from sys.argv
    set_a = sys.argv[1:]
    set_b = ['apple', 'banana', 'mango', 'orange']

    # Call the function with the input sets
    find_common_words(set_a, set_b)