# -*- coding: utf-8 -*-
"""comprehension

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-EkvRshy_CF6Jy2_D5cQt57dkwSTzQ1B
"""

import sys

# Load the command line arguments
my_ints = sys.argv[1:]

# Convert string-type integers to integer-type and apply the transformation
result = [int(x) * 10 if int(x) % 3 == 0 else int(x) for x in my_ints]

# Print the result
print(result)