# -*- coding: utf-8 -*-
"""countVowels

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Wkw3HDhM0IB3lU3pAcRA1nG5BTblCR98
"""

import sys

def count_unique_vowels(s):
    # Define a set of vowels
    vowels = set('aeiou')

    # Use set to find unique vowels in the string, converting to lowercase
    unique_vowels = set()
    for char in s.lower():
        if char in vowels:
            unique_vowels.add(char)

    # Print the number of unique vowels
    print(len(unique_vowels))

if __name__ == "__main__":
    # Check if the input string is provided as a command line argument
    if len(sys.argv) > 1:
        input_string = sys.argv[1]
    else:
        # Read input from standard input if no command line argument is provided
        input_string = input().strip()

    # Call the function with the input string
    count_unique_vowels(input_string)

