# -*- coding: utf-8 -*-
"""counter

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zDiy9Vt6s184iF9WIQTG4hJkOi9IFlvI
"""

import sys
from collections import OrderedDict

# Load the command line argument
word = sys.argv[1]

# Create an ordered dictionary to store the counts
letter_count = OrderedDict()

# Count the occurrences of each letter in the order of their appearance
for letter in word:
    if letter in letter_count:
        letter_count[letter] += 1
    else:
        letter_count[letter] = 1

# Convert OrderedDict to a regular dictionary and print the result
print(dict(letter_count))