# -*- coding: utf-8 -*-
"""diffset

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GCAqsvhHXf5Osnhc1l5MTDhqz1L75445
"""

import sys

def find_difference(set_a, set_b):
    # Convert lists to sets
    set_a = set(set_a)
    set_b = set(set_b)

    # Find words that exist in set_a but are not in set_b
    difference = set_a.difference(set_b)

    # Print the difference in set format
    print(difference)

if __name__ == "__main__":
    # Load the variables from sys.argv
    set_a = sys.argv[1:]
    set_b = ['apple', 'banana', 'mango', 'orange']

    # Call the function with the input sets
    find_difference(set_a, set_b)