# -*- coding: utf-8 -*-
"""duckgoose

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FnP08a0vWpT2g7Ul42Xi04IhDNc7pidu
"""

import sys

# Load the command line arguments
duck_goose = sys.argv[1:]

# Remove all 'goose' from the list
result = [word for word in duck_goose if word != 'goose']

# Print the remaining list
print(result)