# -*- coding: utf-8 -*-
"""duplicates

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1j-FZ5u_MVpFUJDEzMRu-OZ5WuPE7jJ28
"""

import sys


duplicated_words = sys.argv[1:]


unique_words = list(set(duplicated_words))


unique_words.sort(reverse=True)


print(unique_words)