# -*- coding: utf-8 -*-
"""fastfood

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jPhi5vKX2Xm-sL6FGrPHng0s-9a9VPkC
"""

import sys
import pandas as pd
import statsmodels.api as sm

# Check if the argument is provided
if len(sys.argv) > 1:
    csv_file = sys.argv[1]
else:
    # Default to 'fastfood.csv' if no argument is provided
    csv_file = 'fastfood.csv'

# Load the CSV file
data = pd.read_csv(csv_file)

# Define the independent variables and dependent variable
X = data[['total_fat', 'sat_fat', 'cholesterol', 'sodium']]
y = data['calories']

# Add a constant to the independent variables
X = sm.add_constant(X)

# Fit the regression model
model = sm.OLS(y, X).fit()

# Print the required outputs rounded to two decimals
print(model.mse_total.round(2))
print(model.rsquared.round(2))
print(model.params.round(2))
print(model.pvalues.round(2))