# -*- coding: utf-8 -*-
"""german

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1THrpbJj2JmUT5q9S9d69vNedUBgwe4Gx
"""

import sys
import pandas as pd
import statsmodels.api as sm

# Check if the argument is provided
if len(sys.argv) > 1:
    csv_file = sys.argv[1]
else:
    # Default to 'german_credit_data.csv' if no argument is provided
    csv_file = 'german_credit_data.csv'

# Load the CSV file
data = pd.read_csv(csv_file)

# Rename the column 'Credit amount' to 'Credit_amount'
data.rename(columns={'Credit amount': 'Credit_amount'}, inplace=True)

# Define the independent variables and dependent variable
X = data[['Age', 'Duration']]
y = data['Credit_amount']

# Add a constant to the independent variables
X = sm.add_constant(X)

# Fit the regression model
model = sm.OLS(y, X).fit()

# Print the required outputs rounded to two decimals
print(model.params.round(2))
print(model.rsquared.round(2))