# -*- coding: utf-8 -*-
"""gpacalc

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_NJlB6YjLkQ0pnfliwxUL1ss3CkKDUfQ
"""

import sys

def calculate_gpa(grades):
    gpa_dict = {
        'A': 4.0, 'A-': 3.66, 'B+': 3.33, 'B': 3.0, 'B-': 2.66,
        'C+': 2.33, 'C': 2.0, 'C-': 1.66, 'D+': 1.33, 'D': 1.00,
        'D-': 0.66, 'F': 0.00
    }

    # Convert grades to uppercase and calculate GPA
    total_gpa = sum(gpa_dict[grade.upper()] for grade in grades)
    average_gpa = total_gpa / len(grades)

    # Print the GPA in the required format
    print(f"My GPA is {average_gpa:.2f}")

if __name__ == "__main__":
    # Check if the input grades are provided as command line arguments
    if len(sys.argv) > 4:
        input_grades = sys.argv[1:5]
    else:
        # Read input from standard input if not enough command line arguments are provided
        input_grades = [input().strip() for _ in range(4)]

    # Call the function with the input grades
    calculate_gpa(input_grades)