# -*- coding: utf-8 -*-
"""grades

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QcqFF001L4K1dhJN-LvK9-Rh1WO_TSIm
"""

import sys

def calculate_average_excluding_subject(subject):
    grades = {
        'Biology': 80,
        'Physics': 88,
        'Chemistry': 98,
        'Math': 89,
        'English': 79,
        'Music': 67,
        'History': 68,
        'Art': 53,
        'Economics': 95,
        'Psychology': 88
    }

    # Check if the subject is in the dictionary
    if subject in grades:
        # Remove the subject from the dictionary
        del grades[subject]

        # Calculate the average score excluding the subject
        average_score = sum(grades.values()) / len(grades)

        # Print the average score to two decimals
        print(f"{average_score:.2f}")
    else:
        print("Subject not found")

if __name__ == "__main__":
    # Check if the input string is provided as a command line argument
    if len(sys.argv) > 1:
        input_subject = sys.argv[1]
    else:
        # Read input from standard input if no command line argument is provided
        input_subject = input().strip()

    # Call the function with the input subject
    calculate_average_excluding_subject(input_subject)