# -*- coding: utf-8 -*-
"""inrange

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JFouf5HFTmvF7ctSHs6qvvwUp54JZDry
"""

import sys

def find_divisible_values(n):
    # Define the range
    start = 3000
    end = 5000

    # Calculate the divisors
    divisors = [n, n + 7, n ** 2]

    # Find values in the range that are divisible by all of the divisors
    divisible_values = [i for i in range(start, end + 1) if all(i % d == 0 for d in divisors)]

    # Print the list of divisible values
    print(divisible_values)

if __name__ == "__main__":
    # Check if the input integer is provided as a command line argument
    if len(sys.argv) > 1:
        try:
            input_integer = int(sys.argv[1])
        except ValueError:
            print("Please provide a valid integer argument.")
            sys.exit(1)
    else:
        # Read input from standard input if no command line argument is provided
        input_integer = int(input().strip())

    # Call the function with the input integer
    find_divisible_values(input_integer)