# -*- coding: utf-8 -*-
"""loopindex

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1U_drg5xftIzrJbzzmduql1U3dAx4Tfqr
"""

import sys

# Load the command line arguments
loop_list = sys.argv[1:]

# Convert string-type integers to integer-type and add their index position
result = [int(x) + i for i, x in enumerate(loop_list)]

# Print the result
print(result)