# -*- coding: utf-8 -*-
"""luke

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1s8llvWlw4KYZHsoyZ4T5toP4QqMJAK34
"""

import sys

def luke_relation(key):
    relations = {
        'Darth Vader': 'father',
        'Leia': 'sister',
        'Han': 'brother in law',
        'R2D2': 'droid',
        'Rey': 'Padawan',
        'Tatooine': 'homeworld'
    }

    # Check if the key is in the dictionary
    if key in relations:
        # Print the appropriate message
        if key == 'Darth Vader':
            print("No, I am your father")
        else:
            print(f"Luke, I am your {relations[key]}")
    else:
        print("Relation not found")

if __name__ == "__main__":
    # Check if the input string is provided as a command line argument
    if len(sys.argv) > 1:
        input_key = sys.argv[1]
    else:
        # Read input from standard input if no command line argument is provided
        input_key = input().strip()

    # Call the function with the input key
    luke_relation(input_key)