# -*- coding: utf-8 -*-
"""palindrome

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Pix-NrpBqGIBmLfdYk2usCYOaPq_3VPU
"""

import sys
import re

def is_palindrome(s):
    # Remove non-alphanumeric characters and convert to lowercase
    cleaned_string = re.sub(r'[^a-zA-Z0-9]', '', s).lower()

    # Check if the cleaned string is a palindrome
    if cleaned_string == cleaned_string[::-1]:
        print("It's a palindrome!")
    else:
        print("It's not a palindrome!")

if __name__ == "__main__":
    # Check if the input string is provided as a command line argument
    if len(sys.argv) > 1:
        input_string = sys.argv[1]
    else:
        # Read input from standard input if no command line argument is provided
        input_string = input().strip()

    # Call the function with the input string
    is_palindrome(input_string)