# -*- coding: utf-8 -*-
"""presidents

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qlo-OJSvD8tjMJ8CXSBDMs5XOqmomkm7
"""

import sys

import pandas as pd



def average_height(start, stop):

    df = pd.read_csv("president_heights.csv")

    heights = df["height(cm)"][start:stop]

    avg = round(heights.mean(), 2)

    print(f"The average height of presidents number {start} to {stop} is {avg}")



if __name__ == "__main__":

    if len(sys.argv) != 3:

        print("Usage: python presidents.py <start> <stop>")

    else:

        start = int(sys.argv[1])

        stop = int(sys.argv[2])

        average_height(start, stop)

