# -*- coding: utf-8 -*-
"""randdf

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13EotVPqVTbAfl3gwNd3jfaf-c5aCdPl4
"""

import sys

import numpy as np

import pandas as pd



def create_dataframe(rows, cols):

    np.random.seed(56)

    data = np.random.randint(0, 100, size=rows * cols)

    df = pd.DataFrame(data.reshape((rows, cols)))

    print(df)



if __name__ == "__main__":

    if len(sys.argv) != 3:

        print("Usage: python randdf.py <rows> <cols>")

    else:

        rows = int(sys.argv[1])

        cols = int(sys.argv[2])

        create_dataframe(rows, cols)