# -*- coding: utf-8 -*-
"""reallyrandom

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OyixPPu9V2JihZqKfpri94LeBA2_LNB3
"""

import sys

import numpy as np



def generate_random_value(size, multiplier, index):

    np.random.seed(42)

    data = np.random.randint(0, 10, size=size)

    result = data * multiplier

    if index < size:

        print(f"Your random value is {result[index]}")



if __name__ == "__main__":

    if len(sys.argv) != 4:

        print("Usage: python reallyrandom.py <size> <multiplier> <index>")

    else:

        size = int(sys.argv[1])

        multiplier = int(sys.argv[2])

        index = int(sys.argv[3])

        generate_random_value(size, multiplier, index)