# -*- coding: utf-8 -*-
"""sacramento

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IKhCARSMY8s0uf_2AbS2UI4hgLXbUtIu
"""

import sys
import pandas as pd
import statsmodels.api as sm

# Check if the argument is provided
if len(sys.argv) > 1:
    csv_file = sys.argv[1]
else:
    # Default to 'sacramento.csv' if no argument is provided
    csv_file = 'sacramento.csv'

# Load the CSV file
data = pd.read_csv(csv_file)

# Create a new variable from baths
data['bath_binary'] = data['baths'].apply(lambda x: 0 if x == 1 else 1)

# Define the independent variables and dependent variable
X = data[['beds', 'sqft', 'price']]
y = data['bath_binary']

# Add a constant to the independent variables
X = sm.add_constant(X)

# Fit the logistic regression model
model = sm.Logit(y, X).fit()

# Print the required outputs rounded to two decimals
print(model.params.round(2))
print(model.pvalues.round(2))
print('The smallest p-value is for sqft')