# -*- coding: utf-8 -*-
"""shortest

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uw70rBma1-jIhSehT64uz4xBfOWO0KE4
"""

import sys

def find_shortest_word(s):
    # Split the string into words
    words = s.split()

    # Find the shortest word
    shortest_word = min(words, key=len)

    # Print the result in the required format
    print(f"The shortest word is {shortest_word.upper()}")

if __name__ == "__main__":
    # Check if the input string is provided as a command line argument
    if len(sys.argv) > 1:
        input_string = sys.argv[1]
    else:
        # Read input from standard input if no command line argument is provided
        input_string = input().strip()

    # Call the function with the input string
    find_shortest_word(input_string)